
# Diccionario combinado con expansiones principales, menores, promocionales y especiales
cardmarket_set_map = {
    "base1": {"abbreviation": "BS", "name": "Base Set"},
    "base2": {"abbreviation": "JU", "name": "Jungle"},
    "base3": {"abbreviation": "FO", "name": "Fossil"},
    "base4": {"abbreviation": "B2", "name": "Base Set 2"},
    "base5": {"abbreviation": "TR", "name": "Team Rocket"},
    "gym1": {"abbreviation": "GH", "name": "Gym Heroes"},
    "gym2": {"abbreviation": "GC", "name": "Gym Challenge"},
    "neo1": {"abbreviation": "NG", "name": "Neo Genesis"},
    "neo2": {"abbreviation": "NDI", "name": "Neo Discovery"},
    "neo3": {"abbreviation": "NR", "name": "Neo Revelation"},
    "neo4": {"abbreviation": "NDE", "name": "Neo Destiny"},
    "lc": {"abbreviation": "LC", "name": "Legendary Collection"},
    "ecard1": {"abbreviation": "EX", "name": "Expedition Base Set"},
    "ecard2": {"abbreviation": "AQ", "name": "Aquapolis"},
    "ecard3": {"abbreviation": "SK", "name": "Skyridge"},
    "ex1": {"abbreviation": "RS", "name": "EX Ruby & Sapphire"},
    "ex2": {"abbreviation": "SS", "name": "EX Sandstorm"},
    "ex3": {"abbreviation": "DR", "name": "EX Dragon"},
    "ex4": {"abbreviation": "MA", "name": "EX Team Magma vs Team Aqua"},
    "ex5": {"abbreviation": "HL", "name": "EX Hidden Legends"},
    "ex6": {"abbreviation": "RG", "name": "EX FireRed & LeafGreen"},
    "ex7": {"abbreviation": "TRR", "name": "EX Team Rocket Returns"},
    "ex8": {"abbreviation": "DX", "name": "EX Deoxys"},
    "ex9": {"abbreviation": "EM", "name": "EX Emerald"},
    "ex10": {"abbreviation": "UF", "name": "EX Unseen Forces"},
    "ex11": {"abbreviation": "DS", "name": "EX Delta Species"},
    "ex12": {"abbreviation": "LM", "name": "EX Legend Maker"},
    "ex13": {"abbreviation": "HP", "name": "EX Holon Phantoms"},
    "ex14": {"abbreviation": "CG", "name": "EX Crystal Guardians"},
    "ex15": {"abbreviation": "DF", "name": "EX Dragon Frontiers"},
    "ex16": {"abbreviation": "PK", "name": "EX Power Keepers"},
    "dp1": {"abbreviation": "DP", "name": "Diamond & Pearl"},
    "dp2": {"abbreviation": "MT", "name": "Mysterious Treasures"},
    "dp3": {"abbreviation": "SW", "name": "Secret Wonders"},
    "dp4": {"abbreviation": "GE", "name": "Great Encounters"},
    "dp5": {"abbreviation": "MD", "name": "Majestic Dawn"},
    "dp6": {"abbreviation": "LA", "name": "Legends Awakened"},
    "dp7": {"abbreviation": "STF", "name": "Stormfront"},
    "pl1": {"abbreviation": "PL", "name": "Platinum"},
    "pl2": {"abbreviation": "RR", "name": "Rising Rivals"},
    "pl3": {"abbreviation": "SV", "name": "Supreme Victors"},
    "pl4": {"abbreviation": "AR", "name": "Arceus"},
    "hgss1": {"abbreviation": "HS", "name": "HeartGold & SoulSilver"},
    "hgss2": {"abbreviation": "UL", "name": "Unleashed"},
    "hgss3": {"abbreviation": "UD", "name": "Undaunted"},
    "hgss4": {"abbreviation": "TM", "name": "Triumphant"},
    "cl": {"abbreviation": "CL", "name": "Call of Legends"},
    "bw1": {"abbreviation": "BLW", "name": "Black & White"},
    "bw2": {"abbreviation": "EPO", "name": "Emerging Powers"},
    "bw3": {"abbreviation": "NVI", "name": "Noble Victories"},
    "bw4": {"abbreviation": "NXD", "name": "Next Destinies"},
    "bw5": {"abbreviation": "DEX", "name": "Dark Explorers"},
    "bw6": {"abbreviation": "DRX", "name": "Dragons Exalted"},
    "bw7": {"abbreviation": "BCR", "name": "Boundaries Crossed"},
    "bw8": {"abbreviation": "PLS", "name": "Plasma Storm"},
    "bw9": {"abbreviation": "PLF", "name": "Plasma Freeze"},
    "bw10": {"abbreviation": "PLB", "name": "Plasma Blast"},
    "bw11": {"abbreviation": "LTR", "name": "Legendary Treasures"},
    "xy0": {"abbreviation": "KSS", "name": "Kalos Starter Set"},
    "xy1": {"abbreviation": "XY", "name": "XY"},
    "xy2": {"abbreviation": "FLF", "name": "Flashfire"},
    "xy3": {"abbreviation": "FFI", "name": "Furious Fists"},
    "xy4": {"abbreviation": "PHF", "name": "Phantom Forces"},
    "xy5": {"abbreviation": "PRC", "name": "Primal Clash"},
    "xy6": {"abbreviation": "ROS", "name": "Roaring Skies"},
    "xy7": {"abbreviation": "AOR", "name": "Ancient Origins"},
    "xy8": {"abbreviation": "BKT", "name": "BREAKthrough"},
    "xy9": {"abbreviation": "BKP", "name": "BREAKpoint"},
    "xy10": {"abbreviation": "FCO", "name": "Fates Collide"},
    "xy11": {"abbreviation": "STS", "name": "Steam Siege"},
    "xy12": {"abbreviation": "EVO", "name": "Evolutions"},
    "sm1": {"abbreviation": "SUM", "name": "Sun & Moon"},
    "sm2": {"abbreviation": "GRI", "name": "Guardians Rising"},
    "sm3": {"abbreviation": "BUS", "name": "Burning Shadows"},
    "sm4": {"abbreviation": "CIN", "name": "Crimson Invasion"},
    "sm5": {"abbreviation": "UPR", "name": "Ultra Prism"},
    "sm6": {"abbreviation": "FLI", "name": "Forbidden Light"},
    "sm7": {"abbreviation": "CES", "name": "Celestial Storm"},
    "sm7.5": {"abbreviation": "DRM", "name": "Dragon Majesty"},
    "sm8": {"abbreviation": "LOT", "name": "Lost Thunder"},
    "sm9": {"abbreviation": "TEU", "name": "Team Up"},
    "sm10": {"abbreviation": "UNB", "name": "Unbroken Bonds"},
    "sm11": {"abbreviation": "UNM", "name": "Unified Minds"},
    "sm12": {"abbreviation": "CEC", "name": "Cosmic Eclipse"},
    "swsh1": {"abbreviation": "SSH", "name": "Sword & Shield"},
    "swsh2": {"abbreviation": "RCL", "name": "Rebel Clash"},
    "swsh3": {"abbreviation": "DAA", "name": "Darkness Ablaze"},
    "swsh4": {"abbreviation": "VIV", "name": "Vivid Voltage"},
    "swsh5": {"abbreviation": "BST", "name": "Battle Styles"},
    "swsh6": {"abbreviation": "CRE", "name": "Chilling Reign"},
    "swsh7": {"abbreviation": "EVS", "name": "Evolving Skies"},
    "swsh8": {"abbreviation": "FST", "name": "Fusion Strike"},
    "swsh9": {"abbreviation": "BRS", "name": "Brilliant Stars"},
    "swsh10": {"abbreviation": "ASR", "name": "Astral Radiance"},
    "swsh10.5": {"abbreviation": "PGO", "name": "Pokemon GO"},
    "swsh11": {"abbreviation": "LOR", "name": "Lost Origin"},
    "swsh12": {"abbreviation": "SIT", "name": "Silver Tempest"},
    "swsh12.5": {"abbreviation": "CRZ", "name": "Crown Zenith"},
    "sv01": {"abbreviation": "SVI", "name": "Scarlet & Violet"},
    "sv02": {"abbreviation": "PAL", "name": "Paldea Evolved"},
    "sv03": {"abbreviation": "OBF", "name": "Obsidian Flames"},
    "sv03.5": {"abbreviation": "MEW", "name": "151"},
    "sv04": {"abbreviation": "PAR", "name": "Paradox Rift"},
    "sv04.5": {"abbreviation": "PAF", "name": "Paldean Fates"},
    "sv08": {"abbreviation": "SSP", "name": "Surging Sparks"},
    "sv08.5": {"abbreviation": "PRE", "name": "Prismatic Evolutions"},
    "basep": {"abbreviation": "WP", "name": "Wizards Black Star Promos"},
    "np": {"abbreviation": "NBSP", "name": "Nintendo Black Star Promos"},
    "dpp": {"abbreviation": "DPBP", "name": "DP Black Star Promos"},
    "hgssp": {"abbreviation": "HGSSP", "name": "HGSS Black Star Promos"},
    "bwp": {"abbreviation": "BWP", "name": "BW Black Star Promos"},
    "xyp": {"abbreviation": "XYP", "name": "XY Black Star Promos"},
    "smp": {"abbreviation": "SM", "name": "SM Black Star Promos"},
    "swshp": {"abbreviation": "SWSHP", "name": "SWSH Black Star Promos"},
    "svp": {"abbreviation": "SVP", "name": "SV Black Star Promos"},
    "pop1": {"abbreviation": "POP1", "name": "POP Series 1"},
    "pop2": {"abbreviation": "POP2", "name": "POP Series 2"},
    "pop3": {"abbreviation": "POP3", "name": "POP Series 3"},
    "pop4": {"abbreviation": "POP4", "name": "POP Series 4"},
    "pop5": {"abbreviation": "POP5", "name": "POP Series 5"},
    "pop6": {"abbreviation": "POP6", "name": "POP Series 6"},
    "pop7": {"abbreviation": "POP7", "name": "POP Series 7"},
    "pop8": {"abbreviation": "POP8", "name": "POP Series 8"},
    "pop9": {"abbreviation": "POP9", "name": "POP Series 9"},
    "2011bw": {"abbreviation": "MCD11", "name": "McDonald's Collection 2011"},
    "2012bw": {"abbreviation": "MCD12", "name": "McDonald's Collection 2012"},
    "2014xy": {"abbreviation": "MCD14", "name": "McDonald's Collection 2014"},
    "2015xy": {"abbreviation": "MCD15", "name": "McDonald's Collection 2015"},
    "2016xy": {"abbreviation": "MCD16", "name": "McDonald's Collection 2016"},
    "2017sm": {"abbreviation": "MCD17", "name": "McDonald's Collection 2017"},
    "2018sm": {"abbreviation": "MCD18", "name": "McDonald's Collection 2018"},
    "2019sm": {"abbreviation": "MCD19", "name": "McDonald's Collection 2019"},
    "2021swsh": {"abbreviation": "MCD21", "name": "McDonald's Collection 2021"},
    "bog": {"abbreviation": "BOG", "name": "Best of Game"},
    "P-A": {"abbreviation": "PROA", "name": "Promos-A"},
    "si": {"abbreviation": "SI", "name": "Southern Islands"},
    "ru1": {"abbreviation": "RUM", "name": "Pokémon Rumble"},
    "g1": {"abbreviation": "GEN", "name": "Generations"},
    "dc1": {"abbreviation": "DCR", "name": "Double Crisis"},
    "slg": {"abbreviation": "SLG", "name": "Shining Legends"},
    "sma": {"abbreviation": "smA", "name": "Sun % Moon Starter Set"},
    "kss": {"abbreviation": "KSS", "name": "XY Kalos Starter Set"},
    "drm": {"abbreviation": "DRM", "name": "Dragon Majesty"},
    "det": {"abbreviation": "DET", "name": "Detective Pikachu"},
    "sm115": {"abbreviation": "HIF", "name": "Hidden Fates"},
    "swsh3.5": {"abbreviation": "CPA", "name": "Champion’s Path"},
    "swsh4.5": {"abbreviation": "SHF", "name": "Shining Fates"},
    "pgo": {"abbreviation": "PGO", "name": "Pokémon GO"},
    "cel25": {"abbreviation": "CEL", "name": "Celebrations"},
    "tt2022": {"abbreviation": "BOO", "name": "Trick or Trade 2022"},
    "tt2023": {"abbreviation": "BOO23", "name": "Trick or Trade 2023"},
    "tt2024": {"abbreviation": "BOO24", "name": "Trick or Trade 2024"},
    "sv05": {"abbreviation": "TEF", "name": "Temporal Forces"},
    "sv06": {"abbreviation": "TWM", "name": "Twilight Masquerade"},
    "sv06.5": {"abbreviation": "SFA", "name": "Shrouded Fable"},
    "sv07": {"abbreviation": "SCR", "name": "Stellar Crown"},
    "sv09": {"abbreviation": "JTG", "name": "Journey Together"},
    "sv10": {"abbreviation": "DRI", "name": "Destined Rivals"},
    "pre": {"abbreviation": "PRE", "name": "Prismatic Evolutions"},
    "pfa": {"abbreviation": "PFA", "name": "Paldean Fates"},
    "sfa": {"abbreviation": "SFA", "name": "Shrouded Fable"},
    "mewe": {"abbreviation": "MEW", "name": "151"},
    "2022mcd": {"abbreviation": "MCD22", "name": "McDonald's Match Battle 2022"},
    "2023mcd": {"abbreviation": "MCD23", "name": "McDonald's Match Battle 2023"},
    "2024mcd": {"abbreviation": "M24", "name": "McDonald's Dragon Discovery"},
    "tk-ex-latia": {"abbreviation": "TK1", "name": "EX Trainer Kit"},
    "tk-ex-latio": {"abbreviation": "TK1", "name": "EX Trainer Kit"},
    "tk-ex-n": {"abbreviation": "TK2", "name": "EX Trainer Kit 2"},
    "tk-ex-p": {"abbreviation": "TK2", "name": "EX Trainer Kit 2"},
    "tk-dp-l": {"abbreviation": "TK3", "name": "DP Trainer Kit"},
    "tk-dp-m": {"abbreviation": "TK3", "name": "DP Trainer Kit"},
    "tk-hs-g": {"abbreviation": "TK4", "name": "HS Trainer Kit"},
    "tk-hs-r": {"abbreviation": "TK4", "name": "HS Trainer Kit"},
    "tk-bw-e": {"abbreviation": "TK5", "name": "BW Trainer Kit"},
    "tk-bw-z": {"abbreviation": "TK5", "name": "BW Trainer Kit"},
    "tk-xy-b": {"abbreviation": "TK6", "name": "XY Trainer Kit: Bisharp & Wigglytuff"},
    "tk-xy-w": {"abbreviation": "TK6", "name": "XY Trainer Kit: Bisharp & Wigglytuff"},
    "tk-xy-sy": {"abbreviation": "TK7", "name": "XY Trainer Kit"},
    "tk-xy-n": {"abbreviation": "TK7", "name": "XY Trainer Kit"},
    "tk-xy-latia": {"abbreviation": "TK8", "name": "XY Trainer Kit: Latias & Latios"},
    "tk-xy-latio": {"abbreviation": "TK8", "name": "XY Trainer Kit: Latias & Latios"},
    "tk-xy-p": {"abbreviation": "TK9", "name": "XY Trainer Kit: Pikachu Libre & Suicune"},
    "tk-xy-su": {"abbreviation": "TK9", "name": "XY Trainer Kit: Pikachu Libre & Suicune"},
    "tk-sm-l": {"abbreviation": "TK10", "name": "SM Trainer Kit: Lycanroc & Alolan Raichu"},
    "tk-sm-r": {"abbreviation": "TK10", "name": "SM Trainer Kit: Lycanroc & Alolan Raichu"},
    "tksas": {"abbreviation": "TK11", "name": "SM Trainer Kit: Alolan Sandslash & Alolan Ninetales"},
    "tksan": {"abbreviation": "TK11", "name": "SM Trainer Kit: Alolan Sandslash & Alolan Ninetales"},
    "A1": {"abbreviation": "A1", "name": "Genetic Apex"},
    "A1a": {"abbreviation": "A1a", "name": "Mythical Island"},
    "A2": {"abbreviation": "A2", "name": "Space-Time Smackdown"},
    "col1": {"abbreviation": "CL", "name": "Call of Legends"},
    "ex5.5": {"abbreviation": "SM-P", "name": "Sun & Moon Promos"},
    "2018fr": {"abbreviation": "MCD18F", "name": "McDonald's Collection 2018 FR"},
    "2019fr": {"abbreviation": "MCD19F", "name": "McDonald's Collection 2019 FR"},
    "mcdp": {"abbreviation": "MCDP", "name": "McDonald's Pokémon-e Minimum Pack"},
    "2025swsh": {"abbreviation": "MCD25", "name": "McDonald's Collection 25th Anniversary"}



}


